# Generated by Django 5.1.1 on 2024-09-09 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Слаг')),
                ('named_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название урла')),
                ('menu_name', models.CharField(max_length=50, verbose_name='Название меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menu')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
